/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'angel' at '10/08/15 11:09 PM' with Gradle 2.3
 *
 * @author angel, @date 10/08/15 11:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
